---
title: "PAM-Trends"
subtitle: "Long-Term Trends and Environmental Variables"
page-layout: full
---

## Goal and Target Outcome

Integration of PAM and environmental data to support climate change investigations by developing new tools that can be applied to all regions and species of interest. To advance data integration in support of creating tools for climate change applications with PAM data and to develop new tools for integration of PAM and environmental data to support climate change investigations.

## Summary

We will create a streamlined workflow to integrate PAM data with necessary ancillary datasets to address questions relevant to climate change and long-term species trends. This workflow will include: identifying PAM data to be included; identifying the climatological data to be included; creating tools for accessing, formatting, and integrating a subset of these data streams; and using these tools and approaches broadly across all regions and species of interest.

The first goal of this project is to compare humpback whale occurrence trends nationwide. All regions will submit and format their humpback detection data into the Passive Acoustic Cetacean Map database.

The second goal will be to identify and create tools to access and apply relevant climate data on the humpback whale dataset.

This workflow will allow for a national comparison of one species to be able to identify and compare changes (or lack thereof) within and across regions. Once this structure has been established, these standardized data formats, tools, and environmental data streams can be applied across the range of project goals and regional needs, including regional-specific high-profile species. This project directly supports the PAM SI objective to advance PAM data analysis and integration approaches with an emphasis on addressing long-term trends.


## Action Items

[Data Identification: Species and Environmental Variables](https://nmfs-ost.github.io/PAM-Trends/content/dataID.html)

[Format Data to PACM/MAKARA](https://nmfs-ost.github.io/PAM-Trends/content/formatData.html)

[Access & Aggregate Data on PACM/MAKARA](https://nmfs-ost.github.io/PAM-Trends/content/dataAccess.html)

[Develop and Refine Workflow](https://nmfs-ost.github.io/PAM-Trends/content/workflow.html)

[Identify Additional Data](https://nmfs-ost.github.io/PAM-Trends/content/newData.html)

[Develop Output Products](https://nmfs-ost.github.io/PAM-Trends/content/dataProducts.html)

[Aspirational Next Steps](https://nmfs-ost.github.io/PAM-Trends/content/nextSteps.html)
